config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets

  # 追加: 投稿ページ用のルート
  get '/hokkaido', to: 'tweets#hokkaido', as: 'hokkaido_tweets' # 北海道の投稿ページ
  post '/hokkaido', to: 'tweets#create' # 北海道の投稿フォームからのPOSTリクエスト

  get '/totigi', to: 'tweets#totigi', as: 'totigi_tweets' # 
  post '/totigi', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/tokyo', to: 'tweets#tokyo', as: 'tokyo_tweets' # 東京の投稿ページ
  post '/tokyo', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/kyoto', to: 'tweets#kyoto', as: 'kyoto_tweets' # 
  post '/kyoto', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/oosaka', to: 'tweets#oosaka', as: 'oosaka_tweets' # 
  post '/oosaka', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/fukuyama', to: 'tweets#fukuyama', as: 'fukuyama_tweets' # 
  post '/fukuyama', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/hirosima', to: 'tweets#hirosima', as: 'hirosima_tweets' # 
  post '/hirosima', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/fukuoka', to: 'tweets#fukuoka', as: 'fukuoka_tweets' # 福岡の投稿ページ
  post '/fukuoka', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト

  get '/test', to: 'tweets#test', as: 'test_tweets' # 福岡の投稿ページ
  post '/test', to: 'tweets#create' # 投稿フォームからのPOSTリクエスト



  # 他のルート定義

  # Defines the root path route ("/")
  # root "articles#index"
  get '/itiran', to: 'tweets#itiran', as: 'itiran'

  get '/explanation', to: 'tweets#explanation', as: 'explanation'

end

app/models/application_record.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  
  has_one_attached :image

  validates :title, presence: true
  validates :introduction, presence: true
  validates :user_id, presence: true

  attribute :title, :string
  attribute :introduction, :text

end

app/models/user.rb
class User < ApplicationRecord

  has_many :tweets, dependent: :destroy

  validates :nickname, presence: true, length: { maximum: 6 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_region

  def index
    @tweets = Tweet.where(region: @region)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      case params[:tweet][:region]
      when 'hokkaido'
        redirect_to hokkaido_path, notice: 'Tweet was successfully created.'
      when 'totigi'
        redirect_to totigi_path, notice: 'Tweet was successfully created.'
      when 'tokyo'
        redirect_to tokyo_path, notice: 'Tweet was successfully created.'
      when 'oosaka'
        redirect_to oosaka_path, notice: 'Tweet was successfully created.'
      when 'kyoto'
        redirect_to kyoto_path, notice: 'Tweet was successfully created.'
      when 'fukuyama'
        redirect_to fukuyama_path, notice: 'Tweet was successfully created.'
      when 'hirosima'
        redirect_to hirosima_path, notice: 'Tweet was successfully created.'
      when 'fukuoka'
        redirect_to fukuoka_path, notice: 'Tweet was successfully created.'
      else
        redirect_to root_path, notice: 'Tweet was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @region = @tweet.region
    if @tweet.update(tweet_params)
      redirect_to "/#{@region}.html", notice: 'ツイートが更新されました。'
    else
      render :edit
    end
  end

  
  def destroy
    @tweet = Tweet.find(params[:id])
    @region = @tweet.region
    @tweet.destroy
    redirect_to "/#{@region}.html", notice: 'ツイートが削除されました。'
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end


  def itiran
    render 'itiran' 
  end

  def hokkaido
    @tweets = Tweet.where(region: 'hokkaido')
  end

  def  totigi
    @tweets = Tweet.where(region: 'totigi')
  end

  def tokyo
    @tweets = Tweet.where(region: 'tokyo')
  end

  def kyoto
    @tweets = Tweet.where(region: 'kyoto')
  end

  def oosaka
    @tweets = Tweet.where(region: 'oosaka')
  end

  def fukuyama
    @tweets = Tweet.where(region: 'fukuyama')
  end

  def hirosima
    @tweets = Tweet.where(region: 'hirosima')
  end

  def fukuoka
    @tweets = Tweet.where(region: 'fukuoka')
  end

  def test
    @tweets = Tweet.where(region: 'test')
  end


  def explanation
    @tweets = Tweet.where(region: 'explanation')
    render 'explanation' 
  end


  private

  def tweet_params
    params.require(:tweet).permit(:title, :image, :introduction, :region)
  end

  def set_region
    @region = params[:region]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<div style="text-align: center;">
  <%= form_with(model: @tweet, url: tweet_path(@tweet), method: :patch, local: true) do |form| %>
    <div class="form-container"> 
      <div class="form-item">
        <%= form.label :title, "タイトル" %>
        <%= form.text_field :title %>
      </div>
      <div class="form-item">
        <%= form.label :image, "画像" %>
        <%= form.file_field :image %>
      </div>
      <div class="form-item">
        <%= form.label :introduction, "紹介文" %>
        <%= form.text_area :introduction %>
      </div>
      <%= button_to '更新', tweet_path(@tweet), method: :patch, class: "submit-button", remote: true %>
      <%= button_to '削除', tweet_path(@tweet), method: :delete, data: { turbo_method: :delete }, class: "submit-button delete-button" %>
    </div>
  <% end %>
</div>

app/views/tweets/fukuoka.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 福岡県</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("fukuoka.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>福岡県への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: fukuoka_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "fukuoka" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("福岡_マリンメッセ.jpg", class: "post-image") %>
                  <h4>サンプル：福岡県</h4>
                  <p>福岡県といえば食事は長浜ラーメン、もつ鍋、馬刺し観光ではマリンメッセや熊本城があります。加藤清正が当時の最先端技術で造り上げた熊本城は一見の価値あり。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/fukuyama.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 福山市</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("fukuyama.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>福山市への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: fukuyama_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "fukuyama" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("福山_福山城.jpg", class: "post-image") %>
                  <h4>サンプル：広島県福山市</h4>
                  <p>広島県福山市といえば福山城が有名です。春は桜がきれいなので一見の価値あり。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/hirosima.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 広島県</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("hirosima.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>広島県への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: hirosima_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "hirosima" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("広島_お好み焼き.jpg", class: "post-image") %>
                  <h4>サンプル：広島県</h4>
                  <p>広島県といえば、食事はお好み焼きや尾道ラーメンが有名でお好み焼きに関しては外すほうが難しいくらいおいしいです。観光ではカープファンならマツダスタジアムが広島駅から行きやすくなっておりオススメです。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/hokkaido.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 北海道</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("hottkaido.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>北海道への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: hokkaido_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "hokkaido" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <!-- ツイート表示 -->
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("北海道_市場.jpg", class: "post-image") %>
                  <h4>サンプル：北海道</h4>
                  <p>北海道といえば食事は海鮮と味噌ラーメン、観光では定山渓温泉が有名です。行ってみると温泉がプールのようになって水着で入る事もできて予想外でたのしい場所もあります。</p>
                </div>
              </div>
            <% else %>
              <!-- 投稿された画像と紹介文 -->
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/kyoto.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 京都府</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("kyoto.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>京都府への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: kyoto_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "kyoto" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("京都_銀閣寺.jpg", class: "post-image") %>
                  <h4>サンプル：京都府</h4>
                  <p>京都といえば、金閣寺、銀閣寺など文化遺産が数多くあり、１度は見てみたい場所が多々あります。修学旅行の思い出がある人は友人と行ってみるのも面白いかもです。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/oosaka.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 大阪府</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("oosaka.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>大阪府への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: oosaka_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "oosaka" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("大阪_USJ.jpg", class: "post-image") %>
                  <h4>サンプル：大阪府</h4>
                  <p>大阪府にはユニバーサルスタジオジャパンがあり、家族でいってみたい場所です。有名な食事ももんじゃ焼きやたこ焼き、肉吸いと豊富です。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/test.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - テストページ</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("test.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>テストページへの投稿</h1> 
        <h2>実際の投稿はタイトルと画像のみです。</h2> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: test_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "test" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <!-- ツイート表示 -->
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- 投稿がない場合のサンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("testl.jpg", class: "post-image") %>
                  <h4>ｻﾝﾌﾟﾙ：栃木県の華厳の滝</h4>
                  <p>紹介文：栃木県の日光東照宮を見るついでに車で行きました。有料展望台にいく時の通路が夏場でも少し寒く感じるくらいで気持ちよく、展望台に行くと若干水滴が霧のように飛んできて気持ちよく自然から直接力をもらえますのでお勧めの観光地です。</p>
                </div>
              </div>
            <% else %>
              <!-- 投稿された画像と紹介文 -->
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4>タイトル： <%= tweet.title %></h4>
                      <p>紹介文： <%= tweet.introduction %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tweets/tokyo.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>みんなの旅行情報アプリ - 東京都</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="map">
      <div class="map-city">
        <%= image_tag("tokyo.jpg", alt: "Map Image") %>
      </div>
      <div class="map-overlay">
        <h1>東京都への投稿</h1> 
        <!-- 投稿フォーム -->
        <div class="post-form">
          <%= form_with(model: Tweet.new, url: tokyo_tweets_path, local: true) do |form| %>
            <%= form.hidden_field :region, value: "tokyo" %>
            <div class="form-item">
              <%= form.label :title, "タイトル" %>
              <%= form.text_field :title %>
            </div>
            <div class="form-item">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image %>
            </div>
            <div class="form-item">
              <%= form.label :introduction, "紹介文" %>
              <%= form.text_area :introduction %>
            </div>
            <%= form.submit "投稿", style: "border: 1px solid black; padding: 5px; margin-bottom: 10px;" %>
          <% end %>
          <div class="tweets-container">
            <% if @tweets.empty? %>
              <!-- サンプル画像と紹介文 -->
              <div class="tweet">
                <div class="posted-image-container">
                  <%= image_tag("東京_東京駅.jpg", class: "post-image") %>
                  <h4>サンプル：東京都</h4>
                  <p>東京といえば観光地は、東京スカイツリーや東京駅、歌舞伎座や浅草ととにかく観光する場所に困らない地域です。感覚的にはないものがわからないくらいには食事は揃っていますので他の地域から来た際に食べ比べもオススメです。</p>
                </div>
              </div>
            <% else %>
              <% @tweets.reverse_each do |tweet| %>
                <div class="tweet">
                  <% if tweet.image.attached? %>
                    <div class="posted-image-container">
                      <% if current_user == tweet.user %>
                        <%= link_to edit_tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% else %>
                        <%= link_to tweet_path(tweet) do %>
                          <%= image_tag rails_blob_path(tweet.image, only_path: true), class: "post-image" %>
                        <% end %>
                      <% end %>
                      <h4><%= tweet.title %></h4>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>